Repository tcc-lucas-dafne/tcc-password-manager, pull requests merged in 2024-06, with the labels that each got.

#38 Testando release
  src/App.tsx
Labels: MAJOR RELEASE

#39 Testando a release
  src/App.tsx
Labels: MAJOR RELEASE

#43 fix: test release
  src/App.tsx
Labels: MAJOR RELEASE

#44 fix: test release
  src/App.tsx
Labels: MAJOR RELEASE

#47 fix: test release
  src/App.tsx
Labels: MAJOR RELEASE

#48 fix: test release
  src/App.tsx
Labels: MAJOR RELEASE

#49 fix: add consts.js
  src/App.tsx
Labels: MAJOR RELEASE

#50 fix: add consts.js
  src/App.tsx
Labels: MAJOR RELEASE

#51 fix: add consts.js
  src/App.tsx
Labels: MAJOR RELEASE

#52 fix: test minor
  src/App.tsx
Labels: MINOR RELEASE

#53 fix: test minor
  src/App.tsx
Labels: PATCH RELEASE

#54 fix: test minor
  src/App.tsx
Labels: MAJOR RELEASE

#55 fix: test minor
  src/App.tsx
Labels: MAJOR RELEASE

#56 fix: test minor
  src/App.tsx
Labels: MINOR RELEASE

#57 fix: test minor
  src/App.tsx
Labels: PATCH RELEASE

#62 Update release.yaml
  .github/workflows/release.yaml
Labels: MAJOR RELEASE

#65 fix: main release
  .github/workflows/release.yaml
Labels: MAJOR RELEASE

#66 Release 1
  .github/workflows/release.yaml
Labels: MAJOR RELEASE

#68 fix: altera tipos com any
  context/index.tsx
  src/components/Navigation/index.tsx
  src/components/NewCredentialDialog/index.tsx
  src/context/index.tsx
  src/routes.tsx
  src/types.d.ts
Labels: PATCH RELEASE

#67 fix: define padrao minimo de senha para criacao de conta
  package-lock.json
  package.json
  src/components/PasswordRequirements/index.tsx
  src/components/PasswordStrengthMeter/index.tsx
  src/components/PasswordStrengthMeter/style.ts
  src/pages/Register/index.tsx
Labels: PATCH RELEASE

#69 fix: altera acesso a credenciais por id params
  src/components/NewCredentialDialog/index.tsx
  src/context/index.tsx
  src/pages/Home/index.tsx
  src/routes.tsx
  src/services/index.ts
  src/services/manager.ts
Labels: PATCH RELEASE

#70 fix: atualiza dependencias
  package-lock.json
Labels: PATCH RELEASE
